Script started on Fri 15 Mar 2024 02:32:33 PM CDT
[?1034hbash-4.2$ ./BN#[K3
banner_id: 904209081
m: input the number of processes
4
n: input the number of types of resources
3
Max Matrix: input the value of each element left to right, top to bottom
7
5
3
3
2
2
9
0
2
2
2
2
Allocation Matrix: input the value of each element left to right, top to bottom
0
1
0
2
0
0
3
0
2
2
1
1
Available Vector: input the value of each element left to right
3
3
4
The system is safe
The safe sequence is:
1-->3-->0-->2 
A process start to request resources. The process number is: 
1
Each type resource requested by this proess
2
2
^[[A^[[D        1
Requested more than needed, please re-try!
The system is safe
The safe sequence is:
1-->3-->0-->2 
Request approved!
Do you want to try again? Yes press y/Y, otherwise press any other key to quit
u y
A process start to request resources. The process number is: 
0
Each type resource requested by this proess
7
4
3
Requested more than available, please re-try!
Requested more than available, please re-try!
The system is not safe
Your request is declined!
Do you want to try again? Yes press y/Y, otherwise press any other key to quit
exit
bash-4.2$ exit Script done[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kexit Script done, file is Firstname_Lastname.script[C[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.script[1P.scriptB.scriptl.scripta.scriptk.scripte.script_.scriptN.scripte.scriptl.scripts.scripto.scriptn.script3.script
exit
bash: exit: Script: numeric argument required

Script done on Fri 15 Mar 2024 02:35:13 PM CDT
